#!/bin/bash

export geotomLog=/geotom/log/geotomLog/$(date +%F_%T)

echo "Log to" $geotomLog

export PYTHONPATH=/geotom/PyGeotom/src
echo start Measure
python /geotom/PyGeotom/src/geotom/prog/main.py -c cmd.json -s /dev/ttyUSB0 > $geotomLog
echo Measure done
cp autoMes.wen /var/www/html/mes/$(date +%F_%T).wen
cat $geotomLog
/geotom/bin/mail.py -s "Geotom Messung" -t "antoinewiedmer@hotmail.com" -f $geotomLog,autoMes.wen >> $geotomLog
