#!/bin/bash

if [ $(cat /sys/class/gpio/gpio45/value) -eq 0 ] ; then
	echo run autoMes
	./autoMes
	curdate=`date "+%s"`
	echo $(date -d"@$curdate")
	curquarter=$(($curdate - ($curdate % (5* 60))))
	curquarter=$(($curquarter + (7 * 60)))
	echo $(date -d"@$curquarter")
	echo sleepAt $(date -d "@$curquarter")
	ifdown ppp0
	sleep 5
 	rtcwake -m mem -t $(date +%s -d "@$curquarter")
 	sleep 10
 	ifup ppp0
 	sleep 15
	echo rtc0Time $(date) >> dateWake.log
	echo rtc1Time $(hwclock -f /dev/rtc1 -r) >> dateWake.log
else
  	while [ $(cat /sys/class/gpio/gpio45/value) -eq 0 ] 
  	do
  		echo sleep
  		sleep 1
  	done
fi

