#!/bin/bash

if [ $(cat /sys/class/gpio/gpio45/value) -eq 0 ] ; then
	echo run autoMes
	./autoMes
	curdate=`date "+%s"`
	echo $(date -d"@$curdate")
	curquarter=$(($curdate - ($curdate % (20* 60))))
	curquarter=$(($curquarter + (25 * 60)))
	echo $(date -d"@$curquarter")
	echo nextMeasure $(date -d "@$curquarter") >> ../messungen/AutomaticMesureTime
	#ifdown ppp0
	./push_messungen
	sleep 5
 	rtcwake -m mem -t $(date +%s -d "@$curquarter")
 	#sleep 10
 	#ifup ppp0
 	sleep 15
else
  	while [ $(cat /sys/class/gpio/gpio45/value) -eq 1 ] 
  	do
  		echo sleep
  		sleep 1
  	done
fi

